#!/bin/bash
### BEGIN INIT INFO
# Provides:          --
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Automatically control amp.
# Description:       Automatically sends turn on to amp and select hdmi input 1 when starting playing music.
### END INIT INFO

# To install:
# sudo mv turn_on_amp_service /etc/init.d/turn_on_amp_service
# sudo chmod 755 /etc/init.d/turn_on_amp_service
# sudo update-rc.d turn_on_amp_service defaults

get_is_playing(){
    STATUS=$(curl http://127.0.0.1:3000/api/v1/getstate 2> /dev/null);
    STATUS=$(echo $STATUS | grep play);
    IS_PLAYING=${#STATUS};
    IS_PLAYING=$(($IS_PLAYING > 10 ? 1 : 0))
    echo $IS_PLAYING
}

get_is_playing

was_playing=0
is_playing=0

while true; do
    was_playing=$is_playing
    is_playing=$(get_is_playing)
    (( $is_playing == 0)) && (( $was_playing == 1 )); stop_playing=$((1-$?));
    (( $is_playing == 1)) && (( $was_playing == 0 )); start_playing=$((1-$?));
    if [ $start_playing -eq 1 ]; then
        echo "started"
        irsend SEND_ONCE RECEIVER_2064_MAIN POWER_POWER_ON
        sleep 2
        irsend SEND_ONCE RECEIVER_2064_MAIN INPUT_HDMI1
    fi

    if [ $stop_playing -eq 1 ]; then
        echo "stopped"
    fi
    sleep 1

done
